config/routes.rb
Rails.application.routes.draw do    

  resources :categories, only: [:show, :index]

  resources :users do 
    resources :activities
    resources :votes
  end

  post '/activities/:location' => 'activities#location'
  get '/activities/top_ten' => 'activities#top_ten'

  resources :activities do
    resources :votes
  end

  resources :sessions 

  get '/auth/github/callback', to: 'sessions#create'

  get '/user/activities' => 'users#activities'
  
  root 'application#home'

  get '/signin' => 'users#new'
  post '/signin' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

end

app/models/activity.rb
class Activity < ApplicationRecord
    has_many :user_activities
    has_many :users, through: :user_activities
    has_many :votes

    validates :name, presence: true
    validates :name, uniqueness: true
    validates :description, presence:true
    validates :location, presence: true

    #accepts_nested_attributes_for :user_activities, :users

    scope :top_ten, -> {order(created_at: :desc).limit(10)}

    def self.search_by_location(location)
        #find all activities where activity.location.parameterize == location
        Activity.where(location: location)
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :activities
    #see category index, category show

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password 

    has_many :user_activities
    has_many :activities, through: :user_activities
    has_many :votes, through: :activities

    validates :name, presence: true
    validates :password, presence:true
    validates :name, uniqueness: true
    validates :name, length: { minimum: 2 }
    validates :password, length: { in: 6..20 }

    def self.from_omniauth(auth_hash)
        self.where(:email => auth_hash["info"]["email"]).first_or_create do |user|
            user.password = SecureRandom.hex
        end
    end


end

app/models/user_activity.rb
class UserActivity < ApplicationRecord
    belongs_to :user 
    belongs_to :activity

end

app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :activity
    belongs_to :user

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
    before_action :require_login
    
    def new
        @activity = Activity.new
    end

    def create
        @activity = Activity.create(activity_params)
        @user = current_user
        if @activity.valid?
            @user.activities << @activity
            redirect_to activities_path
        else 
           render '/activities/new'
        end
    end

    def edit
        @activity = Activity.find(params[:id])
    end

    def update
        @activity = Activity.find(params[:id])
        @activity.update(activity_params)
        @activity.save
        redirect_to activity_path(@activity)
    end

    def show
        @activity = Activity.find(params[:id])
    end

    def index
        @activities = Activity.all
        @user = current_user
    end

    def location
        @user = current_user
        @activities = Activity.all.search_by_location(params[:":location"])   
        if !@activities.empty?
        else 
            flash[:notice] = "There are no activities in this location yet."
            redirect_to user_path(@user)
        end
    end

    def destroy
        Activity.find(params[:id]).destroy
        redirect_to activities_url
    end

    def top_ten
        @user = current_user
        @activities = Activity.all
        render '/activities/top_ten'
    end

    private

    def activity_params
        params.require(:activity).permit(:name, :description, :location)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def home
    end

    def current_user
        current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]  
    end
    
      def logged_in?
        !!current_user
      end

    def current_activity
      @activity = Activity.find(params[:id])
    end

      private

      def require_login
        unless logged_in?
          flash[:error] = "You must be logged in to access this section"
          redirect_to root_path
        end
      end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def show
        @category = Category.find_by(id: params[:id])
    end

    def index
        @categories = Category.all
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_login, :except => [:new, :create]
    
    def new
        @user = User.new
    end

    def create
        if auth_hash = request.env["omniauth.auth"]
            user = User.from_omniauth(auth_hash)
            session[:user_id] = user.id
            redirect_to user_path(user.id)
        else 
            @user = User.find_by(name: params[:name])
            if @user && @user.authenticate(params[:password])
                session[:user_id] = @user.id
                redirect_to user_path(@user.id)
            else 
                flash[:notice] = "Your username and password do not match- please try again." #this showing up when logging in via github if already logged in to github?
                redirect_to '/sessions/new'
            end
        end
    end

    def destroy
        reset_session     
        redirect_to '/' 
    end

    private

    def user_params
        params.require(:user).permit(:name, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, :except => [:new, :create]
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id
            redirect_to user_path(@user.id)
        else 
            render :new
        end
    end

    def show
        @user = current_user
    end


    def activities
        @user = current_user
        render '/users/activities'
    end

    private

    def user_params
        params.require(:user).permit(:name, :password)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
    before_action :find_activity

    def create
        activity_vote = @activity.votes.new(user_id: current_user.id)
        activity_vote.likes = 1
        activity_vote.save
        redirect_to activity_path(@activity)
    end

    def find_activity
        @activity = Activity.find(params[:activity_id])
    end 
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_form.html.erb
<%= form_for @activity do |f| %>
    <%= f.label :name, 'Activity Name:' %>
    <%= f.text_field :name %>
    
    <%= f.label :description, 'Activity Description' %>
    <%= f.text_area :description %>

    <%= f.label :location, 'Activity Location' %>
    <%= f.select :location, options_for_select([["Select A Zone", ""], "Denver Metro", "Pikes Peak", "Boulder Valley", "Colorado Springs", "Long's Peak", "Northeast Colorado", "Morgan/Washington Bi-County", "East Central Colorado", "Southeast Colorado", "Arkansas Valley", "Southern Colorado", "San Luis Valley", "San Juan Basin", "Western Colorado", "Other"]), :class => 'genForm_dropBox' %>

    <%= f.submit %>
    <%end%>

app/views/activities/edit.html.erb
<%= render 'form' %>

<%= button_to "Delete Activity", activity_path(@activity), method: :delete %>

app/views/activities/index.html.erb
<% @activities.each do |a| %>
    <h3><%= a.name %><br></h3>
    <p><%= a.description %></p>
    <p><%= a.location %> <br></p>
    <% if a.users.include?(@user) %>
        <p><%= link_to "Edit or delete activity", edit_activity_path(a)%></p>
        <% end %>
    <p><%= a.votes.pluck(:likes).count %> likes </p>
    <%= button_to 'Like', activity_votes_path(a), method: :post %>
    <%end%>
<br><br>
<%= link_to "Add an activity", new_user_activity_path(@user) %><br>
<%= link_to "Home", user_path(@user) %>

app/views/activities/location.html.erb
<h1>Activities in <%@activities.each do |a| %>
    <%= a.location %>
    <%end%></h1>

    <% @activities.each do |a| %>
        <h3><%= a.name %><br></h3>
        <p><%= a.description %></p>
        <p><%= a.location %> <br></p>
        <p><%= link_to "Edit or delete activity", edit_activity_path(a)%></p>
        <p><%= a.votes.pluck(:likes).count %> likes </p>
        <%= button_to 'Like', activity_votes_path(a), method: :post %>
    
        <%end%>
    <br><br>
    <%= link_to "Add an activity", new_user_activity_path(@user) %><br>
    <%= link_to "Home", user_path(@user)%>
    

app/views/activities/new.html.erb
<% if @activity.errors.any? %>
  <div id="error_explanation">
    <h2>
      Please try again! <%= pluralize(@activity.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
 
    <ul>
    <% @activity.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form' %>

app/views/activities/show.html.erb
<h1><%= @activity.name %></h1>
<p><%= @activity.description %></p>
<p><%= @activity.location %></p>
<p><%= @activity.votes.pluck(:likes).count %> likes </p>

<%= link_to "Back to My Activities", user_activities_path(@activity) %>
<%= link_to "Back to All Activities", activities_path %>

app/views/activities/top_ten.html.erb
<h1>Most Recently Shared Activities</h1>
<% @activities.top_ten.each do |a| %>
    <h3><%= a.name %><br></h3>
    <p><%= a.description %></p>
    <p>Location: <%= a.location %> <br></p>
    <br>
    <% end %>
    <br>
    

    <%= link_to "Home", user_path(@user) %>

app/views/application/home.html.erb
<h1>Welcome to the Shreddit!</h1>

<%= link_to "Log In", new_session_path %> <br>
<%= link_to "Sign Up", new_user_path %>

<p> Or <%= link_to "Log In Via Github", "/auth/github" %> </p>

app/views/categories/index.html.erb
<% @categories.each do |category| %>
  <h4><%= category.name %></h4>
  <ul>
    <% category.activities.each do |activity| %>
      <li> <%= activity.name %> 
    <% end %>
  </ul>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %> <h1>
<% @category.activities.each do |activity| %>
    <h4><%= activity.name %></h4>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Shreddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= yield %>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

app/views/users/activities.html.erb
<h1>My Activities</h1>

<% @user.activities.each do |a| %>
    <h3><%= a.name %></h3>
    <p><%= a.description %></p>
    <p><%= a.location %></p>
    <p><%=  a.user_activities.pluck(:created_at)[0].strftime("%m-%d-%Y") %></p>
    <p><%= link_to "Edit or delete activity", edit_activity_path(a)%></p>
    <br>
    <%end%>

<%= link_to "Add an activity", new_user_activity_path(@user) %><br>
<%= link_to "View All Activities", activities_path %>

<%= link_to "Home", user_path(@user) %><br>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      Please try again! <%= pluralize(@user.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |f| %>
    <%= f.label :name, 'Username:' %>
    <%= f.text_field :name %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit %>
    <%end%>

app/views/users/show.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

<h1> Welcome, <%= @user.name %>!</h1>
<p>You have <%= @user.votes.pluck(:likes).count%> likes</p>

<p><%= link_to "Add an activity", new_user_activity_path(@user.id) %></p>

<p><%= link_to "View Your Activities", :controller => :users, :action => :activities%></p>

<p><%= link_to "View All Activities", activities_path %></p>

<%= link_to "Most Recent Activities", activities_top_ten_path %>
<br>
<br>
<%= form_tag('/activities/location') do %>
    <label>View Activities by Location:</label><br>
    <%= select_tag ":location", raw("<option>Denver Metro</option><option>Pikes Peak</option><option>Boulder Valley</option><option>Colorado Springs</option><option>Long's Peak</option><option>Northeast Colorado</option><option>Morgan/Washington Bi-County</option><option>East Central Colorado</option>
    <option>Southeast Colorado</option><option>Arkansas Valley</option><option>Southern Colorado</option><option>San Luis Valley</option><option>San Juan Basin</option><option>Western Colorado</option><option>Other</option>") %>
    <input type="submit" value="Search">
    <%end%>
<br>
<%= link_to "Log Out", session_path, :method => :delete %>